
package org.example.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZodiacSignService", targetNamespace = "http://service.example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZodiacSignService {


    /**
     * 
     * @param month
     * @param year
     * @param day
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getZodiacSign", targetNamespace = "http://service.example.org/", className = "org.example.proxy.GetZodiacSign")
    @ResponseWrapper(localName = "getZodiacSignResponse", targetNamespace = "http://service.example.org/", className = "org.example.proxy.GetZodiacSignResponse")
    @Action(input = "http://service.example.org/ZodiacSignService/getZodiacSignRequest", output = "http://service.example.org/ZodiacSignService/getZodiacSignResponse")
    public String getZodiacSign(
        @WebParam(name = "day", targetNamespace = "")
        int day,
        @WebParam(name = "month", targetNamespace = "")
        int month,
        @WebParam(name = "year", targetNamespace = "")
        int year);

}
